image: alpine

# Cache modules in between jobs
cache:
  key: "master"
  paths:
    - node_modules/

stages:
  - build
  - validate
  - deploy

build-dev:
  stage: build
  script:
    - apk add git npm
    - npm install --verbose
    - npm run build-dev
  except:
    - master
    - test_pages

build-prod:
  stage: build
  script:
    - apk add git npm
    - npm install --verbose
    - npm run build
  except:
    - master
    - test_pages

validate-html:
  stage: validate
  script:
    - apk add git npm
    - npm install --verbose
    - npm install -g html-validator-cli
    - npm run build-dev
    - npm run validate-html
  except:
    - master
  only:
    - test

pages:
  stage: deploy
  script:
    - apk add git npm
    - npm install --verbose
    - npm run build-dev
    - mv dist public
  artifacts:
    paths:
      - public/
  only:
    - master

deploy-ovh:
  stage: deploy
  script:
    - apk add git npm
    - npm install --verbose
    - npm run build

  when: manual