image: mvalois/aura-builder

include:
  - /.SKLT_gitlab-ci/stages.yml
  - /.SKLT_gitlab-ci/policy.yml
  - /.SKLT_gitlab-ci/build.yml
  - /.SKLT_gitlab-ci/deploy.yml

build-dev:
  extends: .build-dev

build-prod:
  extends: .build-prod

validate-html:
  extends: .validate-html
  needs: ["build-dev", "build-prod"]

pages:
  extends: .pages
  script:
    - mkdir public/
    - mv dist/dev/websites/migdal.ovh/* public/
  needs: ["build-dev"]